steps:
  - name: node:16.0.0
    entrypoint: npm
    args: ["install"]
  - name: node:16.0.0
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "MONGO_URI=${_MONGO_URI}"
      - "EMAIL_HOST_ADDRESS=${_EMAIL_HOST_ADDRESS}"
      - "ANDROID_CLIENT_ID=${_ANDROID_CLIENT_ID}"
      - "OAUTH_CLIENT_ID_GOOGLE_SIGNIN=${_OAUTH_CLIENT_ID_GOOGLE_SIGNIN}"
      - "OAUTH_CLIENT_SECRET_GOOGLE_SIGNIN=${_OAUTH_CLIENT_SECRET_GOOGLE_SIGNIN}"
      - "OAUTH_CLIENT_ID=${_OAUTH_CLIENT_ID}"
      - "OAUTH_CLIENT_SECRET=${_OAUTH_CLIENT_SECRET}"
      - "OAUTH_REFRESH_TOKEN=${_OAUTH_REFRESH_TOKEN}"
      - "OAUTH_ACCESS_TOKEN=${_OAUTH_ACCESS_TOKEN}"
      - "ADMIN_EMAIL_ADDRESS=${_ADMIN_EMAIL_ADDRESS}"
      - "ADMIN_EMAIL_1=${_ADMIN_EMAIL_1}"
      - "JWT_SECRET_ACCESS=${_JWT_SECRET_ACCESS}"
      - "JWT_SECRET_REFRESH=${_JWT_SECRET_REFRESH}"
      - "JWT_ACCESS_EXP=${_JWT_ACCESS_EXP}"
      - "JWT_REFRESH_EXP=${_JWT_REFRESH_EXP}"
      - "PORT=${_PORT}"
      - "NODEMAILER_USER=${_NODEMAILER_USER}"
      - "NODEMAILER_PASS=${_NODEMAILER_PASS}"
      - "PAYSTACK_SECRET_KEY=${_PAYSTACK_SECRET_KEY}"
      - "PAYSTACK_PUBLIC_KEY=${_PAYSTACK_PUBLIC_KEY}"
  - name: node:16.0.0
    entrypoint: npm
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"
